"""31-archive collection: generate 29 documentary interiors; two evidence scenes
are generated by build_evidence_models.py. All coordinates are website x/y/z.
Run Blender --background --factory-startup --python art/build_archive_exhibits.py -- --render
"""
import bpy, json, math, sys
from pathlib import Path
from mathutils import Vector
ROOT=Path(__file__).resolve().parents[1]
exec(compile((ROOT/'art/build_project_models.py').read_text(encoding='utf-8').split('report=[]')[0],str(ROOT/'art/build_project_models.py'),'exec'))
PLANS=json.loads((ROOT/'content/archive-exhibits.json').read_text(encoding='utf-8'))

def word(text,x,y,size=.13,width=3.7,part='optical-lenses',material='ceramic'):
    bpy.ops.object.select_all(action='DESELECT')
    curve=bpy.data.curves.new('Documentary typography','FONT');curve.body=text;curve.size=size;curve.resolution_u=2
    obj=bpy.data.objects.new(text,curve);bpy.context.scene.collection.objects.link(obj)
    obj.location=(x,-.151,y);obj.rotation_euler=(math.pi/2,0,0)
    finish(obj,text,material,part);bpy.context.view_layer.update()
    if obj.dimensions.x>width:obj.scale*=width/obj.dimensions.x
    bpy.context.view_layer.objects.active=obj;obj.select_set(True);bpy.ops.object.convert(target='MESH');obj.select_set(False)

def tile(x,y,w,h,text,part='optical-core',colour='ceramic'):
    box(x,y,w,h,colour,depth=.055,z=.083,part=part)
    word(text,x-w/2+.07,y-.045,.115,w-.14,part,'graphite' if colour=='ceramic' else 'ceramic')

def connect(points,colour='amber'):
    line(points,colour,.025,z=.037,part='optical-lenses')

def sequence(names,y=1.7):
    step=3.85/len(names);w=step-.15
    for i,name in enumerate(names):
        x=-1.925+step*(i+.5);tile(x,y,w,.56,name)
        if i:connect([(x-step+w/2,y),(x-w/2,y)])

def build(spec):
    kind=spec['kind'];names=spec['nodes']
    if kind=='profile':
        word('ZL',-1.65,1.68,1.0,1.6,part='optical-core')
        word('LANCE',-1.65,1.31,.19,1.4)
        for i,name in enumerate(names[1:]):tile(.85,2.26-i*.51,1.9,.34,name)
        connect([(-.15,2.1),(.0,2.1),(.0,1.25)])
        word('OPEN TO SOFTWARE ROLES',-1.7,.86,.14)
    elif kind=='contact':
        for i,name in enumerate(names):
            y=2.3-i*.55;disc(-1.55,y,.12,'amber',vertices=24,z=.06);connect([(-1.42,y),(-.9,y)])
            tile(.36,y,2.7,.36,name)
        word('zizhenliu0427',-.8,.72,.13)
    elif kind=='stack':
        for c in range(3):
            for r in range(3):tile(-1.28+c*1.28,2.29-r*.55,1.13,.39,names[r*3+c])
        for x in [-1.28,0,1.28]:connect([(x,1.0),(x,.81)])
    elif kind in ['devices','workstation']:
        box(-.52,1.92,2.65,1.24,'silver',depth=.07,z=.07)
        box(-.52,1.94,2.44,.99,'graphite',depth=.02,z=.12)
        word(names[0],-1.53,2.15,.2,2.1);word(names[1],-1.53,1.72,.13,2.1)
        box(-.52,1.2,.13,.36,'silver');box(-.52,1.02,1.04,.09,'silver')
        box(1.35,1.76,.74,1.49,'silver',depth=.072,z=.075)
        box(1.35,1.8,.59,1.24,'graphite',depth=.02,z=.125)
        for i in range(3):box(1.35,2.1-i*.24,.41,.1,'trace',depth=.02,z=.14)
        word(names[-1],.97,.87,.1,.88)
    elif kind in ['branch','schema','classifier','hierarchy']:
        if kind=='hierarchy':
            tile(0,2.36,1.65,.42,names[0]);connect([(0,2.14),(0,1.9),(-1.06,1.9),(-1.06,1.6)]);connect([(0,1.9),(1.06,1.9),(1.06,1.6)])
            tile(-1.06,1.36,1.6,.48,names[1]);tile(1.06,1.36,1.6,.48,names[2])
            word('DETERMINISTIC ORDER',-1.55,.84,.14)
        else:
            left=names[:3]
            for i,name in enumerate(left):
                y=2.34-i*.55;tile(-1.12,y,1.47,.37,name);connect([(-.37,y),(.03,y),(.03,1.79),(.37,1.79)])
            tile(1.13,1.79,1.46,.6,names[3] if len(names)>3 else 'QUERY')
            if len(names)>4:tile(.9,.92,1.9,.3,names[4],colour='graphite')
    elif kind in ['flow','codec','audio']:
        sequence(names,2.03)
        if kind=='codec':
            for i in range(12):box(-1.76+i*.32,1.05,.23,.42,'silver' if i<4 else 'trace' if i<8 else 'amber',depth=.024+i*.005,z=.063)
            word('DECODE / TRANSFORM / ENCODE',-1.75,.71,.12)
        elif kind=='audio':
            for i in range(7):
                x=-1.7+i*.49;connect([(x,1.0),(x,1.36),(x+.23,1.36),(x+.23,1.0)])
            word('I2S TIMING / SCHEMATIC',-1.6,.71,.12)
        else:
            for i,name in enumerate(['SOURCE','CHECK','PACKAGE','RELEASE']):word(name,-1.87+i*.97,1.32,.09,.87)
            connect([(-1.4,1.04),(1.43,1.04)],'trace')
    elif kind=='photo':
        for i in range(3):
            box(-.93+i*.91,1.98,1.14,.84,['silver','trace','amber'][i],depth=.033,z=.038+i*.042)
        ring(-1.23,1.23,.28,'silver',.035,z=.08)
        disc(-1.23,1.23,.15,'graphite',z=.06,depth=.03)
        for i,name in enumerate(names):word(name,-.7+i*.77,1.2,.105,.72)
        word('COLOUR / DYNAMIC RANGE',-1.65,.85,.14)
    elif kind=='gear':
        for x in [-1.57,-1.1,-.63]:connect([(x,1.25),(x,2.39)],'silver')
        connect([(-1.57,1.81),(-.63,1.81)],'silver');disc(-1.1,2.39,.105,'amber',z=.10,depth=.035)
        for i,name in enumerate(names):tile(.85,2.34-i*.48,1.93,.3,name,colour='graphite')
        word('CIVIC TYPE R / FK8',-1.7,.88,.16)
    elif kind in ['scores','bars']:
        values=spec['values'];maximum=100 if kind=='scores' else max(values)
        for i,(name,value) in enumerate(zip(names,values)):
            y=2.22-i*(.56 if kind=='scores' else .84)
            word(name,-1.83,y+.2,.12,2.4,part='optical-core')
            word(str(value)+('/100' if kind=='scores' else ''),1.08,y+.18,.19,.8,part='optical-core')
            box(0,y,3.72,.16,'silver',depth=.015,z=.009)
            w=3.72*value/maximum;box(-1.86+w/2,y,w,.13,'amber' if i==0 else 'trace',depth=.069,z=.07)
        if kind=='bars':word('SOURCE: PORTFOLIO RECORD',-1.65,.82,.105)
    elif kind=='etl':
        for i in range(5):box(-1.5,1.26+i*.21,.66,.11,'silver',depth=.025,z=.05)
        tile(-.32,1.83,1.13,.95,'PANDAS');connect([(-1.16,1.83),(-.9,1.83)])
        for i in range(3):tile(1.26,2.29-i*.44,1.11,.27,['VALIDATE','NORMALISE','EXPORT'][i])
        connect([(.27,1.83),(.65,1.83)]);word('SEMI-STRUCTURED TO TABLES',-1.7,.84,.12)
    elif kind=='kanban':
        for i,name in enumerate(names):
            x=-1.43+i*.95;box(x,1.75,.79,1.46,'silver',depth=.027,z=.025)
            word(name,x-.33,2.29,.09,.67)
            # Equal placeholder slips represent states, not actual task counts.
            for j in range(2):box(x,1.89-j*.42,.61,.26,'trace' if i<3 else 'amber',depth=.045,z=.078)
        word('SCHEMATIC TASK BOARD',-1.54,.75,.12)
    elif kind=='route':
        coords=[(-1.22,2.22),(1.18,2.22),(1.18,1.2),(-1.22,1.2)]
        connect([*coords,coords[0]],'trace')
        for (x,y),name in zip(coords,names):tile(x,y,1.28,.41,name)
        word('PORT TO EMPTY RETURN',-1.24,1.73,.12,2.6)
    elif kind=='room':
        tile(0,2.27,2.35,.62,'HOST / ROOM CODE');connect([(0,1.95),(0,1.73),(-1.3,1.73),(-1.3,1.58)]);connect([(0,1.73),(1.3,1.73),(1.3,1.58)])
        for x,text in [(-1.3,'JOIN'),(0,'PLAY'),(1.3,'VOTE')]:
            box(x,1.19,.77,.9,'silver',depth=.06,z=.08);tile(x,1.24,.62,.63,text,colour='graphite')
    elif kind=='chat':
        box(-1.13,1.8,1.25,1.78,'silver',depth=.06,z=.05)
        box(-1.13,1.83,1.08,1.52,'graphite',depth=.018,z=.10)
        tile(-1.27,2.18,.69,.28,'TEXT');tile(-.99,1.65,.69,.48,'IMAGE',colour='trace')
        for i,name in enumerate(names):tile(1.12,2.29-i*.5,1.36,.31,name)
        connect([(-.49,1.81),(.42,1.81)])
    elif kind=='tracks':
        for row in range(2):
            y=2.23-row*.96
            for i,name in enumerate(names[row*3:row*3+3]):tile(-1.3+i*1.3,y,1.13,.38,name)
            connect([(-.7,y),(.7,y)],'trace' if row else 'amber')
            word('EXTENSION' if row==0 else 'LEGACY / LOCAL',-1.8,y-.36,.11)
    elif kind=='sensor':
        for i,name in enumerate(names[:3]):tile(-1.46,2.32-i*.45,.87,.27,name)
        connect([(-.99,1.85),(-.37,1.85)]);tile(.08,1.85,.79,.9,'KAFKA')
        tile(1.4,2.22,.87,.41,'SQL');tile(1.4,1.35,.87,.41,'RAG')
        connect([(.5,1.85),(.8,1.85),(.8,2.22),(.95,2.22)]);connect([(.8,1.85),(.8,1.35),(.95,1.35)])
        word('CO2 / TEMPERATURE / HUMIDITY',-1.8,.79,.115)
    elif kind=='cameras':
        for col in range(3):
            for row in range(2):
                x=-1.5+col*.73;y=2.15-row*.65;box(x,y,.62,.48,'silver',depth=.03,z=.035)
                box(x,y,.43,.3,'graphite',depth=.023,z=.075)
        tile(1.22,2.08,1.01,.52,'YOLOv8');tile(1.22,1.35,1.01,.35,'MJPEG')
        connect([(.33,1.81),(.71,1.81)]);word('SCHEMATIC CAMERA LAYOUT',-1.7,.83,.11)
    elif kind=='speech':
        for i in range(22):
            h=.12+.51*abs(math.sin(i*.79));box(-1.74+i*.165,2.25,.082,h,'trace',depth=.03,z=.05)
        sequence(names[:3],1.36);word(names[3],-1.38,.85,.16,3.0)
        word('SCHEMATIC SIGNAL',.5,2.66,.08,1.42)
    elif kind=='dns':
        for y in [2.37,1.85,1.33]:disc(-1.57,y,.13,'silver',z=.066,depth=.04,vertices=24);connect([(-1.41,y),(-.76,y),(-.76,1.85),(-.48,1.85)])
        tile(.07,1.85,1.09,.71,'TCP 443');tile(1.4,1.85,.92,.42,'DNS PIN')
        connect([(.65,1.85),(.91,1.85)]);word('KEEP GOOD / REPLACE SLOW',-1.66,.85,.12)
    elif kind=='lab':
        for i,name in enumerate(names):
            col=i%2;row=i//2;tile(-1.01+col*2.02,2.3-row*.59,1.7,.39,name)
        for y in [2.3,1.71,1.12]:connect([(-.13,y),(.13,y)],'trace')

report=[]
for identifier,spec in PLANS.items():
    scene=bpy.data.scenes.new(spec['key']);bpy.context.window.scene=scene
    box(0,1.7,4.12,2.98,'graphite',depth=.025,z=-.016)
    for x in [-2.04,2.04]:
        for y in [.42,3.01]:disc(x,y,.044,'amber',depth=.024,z=.035,part='optical-lenses',vertices=16)
    word(identifier,.25,3.04,.18,1.3)
    word(spec['heading'],-1.87,2.77,.16,3.77)
    word(spec['caption'],-1.87,.50,.106,3.76)
    word('PROFILE RECORD' if identifier[0]=='P' else 'EXPERIENCE RECORD' if identifier[0]=='I' else 'DOCUMENTARY STUDY',-1.87,.27,.086)
    build(spec)
    pairs={}
    for obj in list(scene.objects):pairs.setdefault((obj['assemblyPart'],obj.data.materials[0].name),[]).append(obj)
    for (part,surface),objects in pairs.items():
        bpy.ops.object.select_all(action='DESELECT')
        for obj in objects:obj.select_set(True)
        bpy.context.view_layer.objects.active=objects[0];bpy.ops.object.join()
        obj=bpy.context.object;obj.name=part+'__'+surface;obj['assemblyPart']=part;obj['portfolioInterior']=True
        scene.cursor.location=(0,0,0);bpy.ops.object.origin_set(type='ORIGIN_CURSOR');bpy.ops.object.transform_apply(location=True,rotation=True,scale=True)
    scene['archiveId']=identifier;scene['evidenceSource']='content/archive-exhibits.json'
    bpy.ops.object.select_all(action='SELECT');output=OUTPUT/(spec['key']+'.glb')
    bpy.ops.export_scene.gltf(filepath=str(output),export_format='GLB',use_selection=True,use_active_scene=True,export_apply=True,export_extras=True,export_cameras=False,export_lights=False)
    report.append(dict(id=identifier,key=spec['key'],meshes=len(scene.objects),triangles=sum(len(p.vertices)-2 for obj in scene.objects for p in obj.data.polygons),bytes=output.stat().st_size))
    scene.render.engine='CYCLES';scene.cycles.samples=12
    scene.render.resolution_x=960;scene.render.resolution_y=690;scene.render.resolution_percentage=100
    scene.world=bpy.data.worlds.new('Archive studio');scene.world.use_nodes=True
    scene.world.node_tree.nodes['Background'].inputs[0].default_value=(.12,.15,.17,1);scene.world.node_tree.nodes['Background'].inputs[1].default_value=.4
    scene.view_settings.view_transform='Standard'
    bpy.ops.object.camera_add(location=(.4,-9,4.1));camera=bpy.context.object;camera.rotation_euler=(Vector((0,0,1.75))-camera.location).to_track_quat('-Z','Y').to_euler();camera.data.type='ORTHO';camera.data.ortho_scale=4.7;scene.camera=camera
    for pos,energy,size in [((-3,-4,6),350,4),((3,-2,4),180,3)]:
        bpy.ops.object.light_add(type='AREA',location=pos);light=bpy.context.object;light.data.energy=energy;light.data.shape='DISK';light.data.size=size;light.rotation_euler=(Vector((0,0,1.7))-light.location).to_track_quat('-Z','Y').to_euler()
    scene.render.image_settings.file_format='PNG';scene.render.filepath=str(RENDERS/(spec['key']+'.png'))
    if '--render' in sys.argv:bpy.ops.render.render(write_still=True)
    print('ARCHIVE_EXHIBIT',report[-1],flush=True)
(ROOT/'art/archive-exhibits-report.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
bpy.ops.wm.save_as_mainfile(filepath=str(ROOT/'art/archive-exhibits.blend'),compress=True)
